# MACs excluded from Kismet's logs via kis_log_device_filter. These
# devices are still tracked live, just not written to the log.
kis_log_device_filter=IEEE802.11,A4:2A:95:9C:8F:F0,block
kis_log_device_filter=IEEE802.11,A4:2A:95:9C:8F:F1,block
kis_log_device_filter=IEEE802.11,A6:2A:95:AC:8F:F0,block
kis_log_device_filter=IEEE802.11,A6:2A:95:AC:8F:F1,block
kis_log_device_filter=Bluetooth,CF:75:C2:11:DA:38,block
kis_log_device_filter=Bluetooth,E7:BA:9C:EE:B9:13,block
kis_log_device_filter=Bluetooth,67:34:41:3D:29:EF,block
kis_log_device_filter=Bluetooth,5A:D8:43:51:D3:7A,block
kis_log_device_filter=Bluetooth,FC:05:BD:86:48:93,block
